# Generated by Django 5.0.6 on 2024-06-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easeveg', '0003_webuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
