# Generated by Django 5.0.6 on 2024-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easeveg', '0004_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
